source 'https://github.com/CocoaPods/Specs.git'
source 'git@192.168.10.44:ip-ios/pods-repo.git'

use_frameworks!
inhibit_all_warnings!

platform :ios, '8.0'


target 'JRSON' do

    # pod 'JRSONDB', :path => '../'
#    pod 'MethodCopyer', :path => '/Users/Jrwong/Desktop/MethodCopyer'
   pod 'MethodCopyer', '~> 1.0.0'
    # pod 'ObjectPool', :path => '/Users/Jrwong/Desktop/ObjectPool'

end









